replicaCount: 1

env: prod

ingress:
  enabled: true
  className: ""
  hosts:
    - host: sample-reactjs.kaiburr.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - sample-reactjs.kaiburr.com