apiVersion: v1
kind: Service
metadata:
  name: service-aws-k8s-react-app
spec:
  selector:
    app: aws-k8s-react-app
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: react-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: sample-reactjs.kaiburr.com
    http:
      paths:
      - backend:
          serviceName: service-aws-k8s-react-app
          servicePort: http
        path: /
        pathType: ImplementationSpecific    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-k8s-react-app-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-k8s-react-app
  template:
    metadata:
      labels:
        app: aws-k8s-react-app
    spec:
      containers:
        - name: aws-k8s-react-app
          image: registry-demo.kaiburr.com/sample/reactjs:1.0_17
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
